nome = str(input('Digite seu nome completo: '))
print('Analisando seu nome...')
print(f'Seu nome em maiúsculas é {nome.upper()}.')
print(f'Seu nome em minúsculas é {nome.lower()}.')
todo = (len(nome) - nome.count(' '))
print(f'Seu nome tem ao todo {todo} letras.')
separa = nome.split()
print(f'Seu primeiro nome é {separa[0]} e ele tem {separa[0]} letras!')